# basic info
user_name: "LucioSunj"
repo_name: "my-arxiv-daily"

show_badge: false
max_results: 50

publish_readme: true
publish_gitpage: true
publish_wechat: false

# file path 
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords
keywords:
  "Robot & Agent":
    filters: ["Embodied Agent", "Robot Learning", "Robot Policy", "Robot Policies", "Human-Robot", "Cross-Embodiment"]
  "Robotic Manipulation":
    filters: ["Robot Manipulation", "Robotic Manipulation", "Grasp", "Robot Grasp", "World Model"]
  "Vision Language Action Model":
    filters: ["Vision-Language-Action Model", "Vision Language Action Model"]
  "Imitation Learning":
    filters: ["Imitation Learning", "Behavior Cloning", "Behavioral Cloning"]
  "Robotic Navigation":
    filters: ["Robot Navigation", "Vision-and-Language Navigation", "Vision Language Navigation", "Vision-Language-Navigation"]
  "VLM":
    filters: ["Vision Language Model", "Vision Language Models", "Vision-Language Model", "Vision-Language Models"]
  "RL Post Training":
    filters: ["Reinforcement Learning LLM", "RLHF", "RL Fine-tuning", "RL Alignment", "RL Vision Language", "RL VLM", "Reinforcement VLM", "RL VLA", "RL VLN", "RL Flow Matching", "RL Diffusion Policy", "RLAIF", "DPO"]
  "World Model":
    filters: ["World Model", "World Models", "Generative World Model", "Latent World Model", "Visual World Model", "Video World Model", "World Foundation Model", "Model-Based Reinforcement Learning", "Model Based Reinforcement Learning", "Model-Based RL", "Dynamics Model", "Environment Model", "Generative Dynamics Model", "PlaNet", "Dreamer", "DreamerV2", "TD-MPC", "TD-MPC2"]
#   "DA & DG":
#     filters: ["Domain Adaptation", "Unsupervised Domain Adaptation", "Source-free Domain Adaptation", "Test-time Domain Adaptation",
#       "Domain Generalization", "Source-free Domain Generalization", "Test-time Domain Generalization"]
#   "Prompt":
#     filters: ["Prompt Tuning", "Prompt Learning", "Prompt", "Prompts"]
#   "Causal Learning":
#     filters: ["Causal Inference", "Causal Model", "Causal Discovery", "Causal Reasoning"]
